//
//  ShowGIPHYPresenter.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowGIPHYPresentationLogic
{
  func presentSomething(response: ShowGIPHY.Something.Response)
}

class ShowGIPHYPresenter: ShowGIPHYPresentationLogic
{
  weak var viewController: ShowGIPHYDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowGIPHY.Something.Response)
  {
    let displayedGIPHY = ShowGIPHY.Something.ViewModel.DisplayedGIPHY(title: response.giphy.title ?? "no data(", url: response.giphy.url ?? "")
    let viewModel = ShowGIPHY.Something.ViewModel(displayedGIPHY: displayedGIPHY)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
