//
//  ShowGIPHYInteractor.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowGIPHYBusinessLogic
{
  func doSomething(request: ShowGIPHY.Something.Request)
}

protocol ShowGIPHYDataStore
{
  //var name: String { get set }
}

class ShowGIPHYInteractor: ShowGIPHYBusinessLogic, ShowGIPHYDataStore
{
  var presenter: ShowGIPHYPresentationLogic?
  var worker: ShowGIPHYWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowGIPHY.Something.Request)
  {
    worker = ShowGIPHYWorker()
    worker?.doSomeWork()
    
    let response = ShowGIPHY.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
