//
//  ListGIPHYsPresenter.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGIPHYsPresentationLogic
{
  func presentSomething(response: ListGIPHYs.FetchList.Response)
}

class ListGIPHYsPresenter: ListGIPHYsPresentationLogic
{
  weak var viewController: ListGIPHYsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListGIPHYs.FetchList.Response)
  {
    var viewModel = ListGIPHYs.FetchList.ViewModel()
    viewModel.displayesGiphies = self.convertGIPHY(giphies: response.giphies ?? [GIPHY]())
    viewController?.displaySomething(viewModel: viewModel)
  }

    func convertGIPHY(giphies: [GIPHY])->[ListGIPHYs.FetchList.ViewModel.DisplayedGIPHY]{
        var arrayOfGiphies = [ListGIPHYs.FetchList.ViewModel.DisplayedGIPHY]()
        for giphy in giphies{
            let disGIPHY = ListGIPHYs.FetchList.ViewModel.DisplayedGIPHY(url: giphy.url, title: giphy.title)
            arrayOfGiphies.append(disGIPHY)
        }
        return arrayOfGiphies
    }
}
