//
//  ListGIPHYsInteractor.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGIPHYsBusinessLogic
{
  func doSomething(request: ListGIPHYs.FetchList.Request)
}

protocol ListGIPHYsDataStore
{
  //var name: String { get set }
}

class ListGIPHYsInteractor: ListGIPHYsBusinessLogic, ListGIPHYsDataStore
{
  var presenter: ListGIPHYsPresentationLogic?
  var worker: ListGIPHYsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListGIPHYs.FetchList.Request)
  {
    worker = ListGIPHYsWorker()
    worker?.doSomeWork()
    
    let response = ListGIPHYs.FetchList.Response()
    presenter?.presentSomething(response: response)
  }
}
