//
//  ListGIPHYsPresenter.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGIPHYsPresentationLogic
{
  func presentSomething(response: ListGIPHYs.FetchList.Response)
}

class ListGIPHYsPresenter: ListGIPHYsPresentationLogic
{
  weak var viewController: ListGIPHYsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListGIPHYs.FetchList.Response)
  {
    let viewModel = ListGIPHYs.FetchList.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
