//
//  ListGIPHYsRouter.swift
//  VIPTest
//
//  Created by Архип on 10/22/17.
//  Copyright (c) 2017 KoshelGROUP. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListGIPHYsRoutingLogic
{
    func routeToShowGIPHYWithSegue(_ segue: UIStoryboardSegue?)
}

protocol ListGIPHYsDataPassing
{
  var dataStore: ListGIPHYsDataStore? { get }
}

class ListGIPHYsRouter: NSObject, ListGIPHYsRoutingLogic, ListGIPHYsDataPassing
{
  weak var viewController: ListGIPHYsViewController?
  var dataStore: ListGIPHYsDataStore?
  
  // MARK: Routing
  
  func routeToShowGIPHYWithSegue(_ segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! ShowGIPHYViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShowGIPHYViewController") as! ShowGIPHYViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ListGIPHYsViewController, destination: ShowGIPHYViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: ListGIPHYsDataStore, destination: inout ShowGIPHYDataStore)
  {
    if let selectedRow = viewController?.collectionView?.indexPathsForSelectedItems?.first?.row
    {
        destination.giphy = source.GIPHIES?[selectedRow]
    }
  }

}
